list_view/urls.py
from django.urls import path
from .views import IndexView, BookDetailView, GenreView

app_name = 'lv-books'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('g/<str:genre>/', GenreView.as_view(), name='genre'),
    path('<slug:slug>/', BookDetailView.as_view(), name='book-detail'),
]

rv/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from rv.views import Sample2View, PostPreLoadTaskView, SinglePostView

app_name = 'rv'

urlpatterns = [
    # extra_context Attribute from ContentMixin - keyword argument for as_view()
    path('', TemplateView.as_view(template_name="rv/sample1.html",
                                  extra_context={
                                      'title': 'Custom Title or Testing TemplateView',
                                      'name': 'Gersi Muca'}
                                  )),
    path('sample2/', Sample2View.as_view(), name='sample2'),

    path('redirect', RedirectView.as_view(url='http://aol.com/'), name='go-to-aol-mail'),
    path('sample3/<int:pk>/', PostPreLoadTaskView.as_view(), name='redirect-task'),
    path('sample4/<int:pk>/', SinglePostView.as_view(), name='singlepost'),  # single post page
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('client.urls')),
    path('t/', include('template_view.urls', namespace='template_view')),
    path('r/', include('redirect_view.urls', namespace='redirect_view')),
    path('d/books/', include('detail_view.urls', namespace='books')),
    path('l/books/', include('list_view.urls', namespace='books')),
    path('f/books/', include('form_view.urls', namespace='books')),
    path('c/books/', include('create_view.urls', namespace='books')),
    path('u/books/', include('update_view.urls', namespace='home')),
]

list_view/models.py
from django.db import models


# Create your models here.

class BooksLV(models.Model):
    # Example model only
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100)
    count = models.IntegerField(null=True, default=0)

list_view/views.py
from django.db.models import F
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from list_view.models import BooksLV


class IndexView(ListView):
    template_name = "list_view/home.html"
    model = BooksLV
    context_object_name = 'books'
    paginate_by = 4

    # queryset = Books.objects.all()[:2]

    def get_queryset(self):
        return BooksLV.objects.all()[:3]


class GenreView(ListView):
    model = BooksLV
    template_name = 'list_view/home.html'
    context_object_name = 'books'
    paginate_by = 2  # Pagination over-write

    def get_queryset(self, *args, **kwargs):
        return BooksLV.objects.filter(genre__icontains=self.kwargs.get('genre'))


class BookDetailView(DetailView):
    model = BooksLV
    template_name = 'list_view/book-detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = BooksLV.objects.filter(slug=self.kwargs.get('slug'))
        post.update(count=F('count') + 1)

        context['time'] = timezone.now()

        return context

list_view/templates/list_view/book-detail.html
    {% extends "detail_view/base.html" %}
    {% block content %}
    <div class="container" style="max-width:800px">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{book.title}}</h1>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{book.genre}}</small>
                <small class="text-muted">{{book.isbn}}</small>
                <small class="text-muted">{{time}}</small>
            </div>
        </div>

    </div>
    {% endblock %}

list_view/templates/list_view/home.html
    {% extends "detail_view/base.html" %}
    {% block content %}
    <div class="container">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">All Books</h1>
            <p class="lead">A range of wonderful programming books to help you learn JavaScript.</p>
        </div>
        <div class="py-5">
            <div class="row">
                {% for book in books %}
                <div class="col-md-4">
                    <a class="text-dark" href="{% url 'lv-books:book-detail' slug=book.slug %}">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                    {{book.title|truncatechars:50}}</h2>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">{{book.genre}}</small>
                                    <small class="text-muted">{{book.isbn}}</small>
                                </div>
                                <small class="text-muted">{{time}}</small>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-12">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}